In [2]:
import pandas as pd
import numpy as np

In [18]:
pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(precision=2)

In [28]:
x1= 10*np.random.randn(2,5)
x1

array([[  4.35, -10.53,  -6.53,  -4.99,   4.21],
       [  5.25,  -1.05,  18.16,   1.43,  -3.38]])

In [29]:
x2= -10*np.random.randn(2,5)
x2

array([[ -1.34,  -4.35,   2.7 ,  26.87,   2.69],
       [-13.09,   6.83,  -2.84,   5.46,  -8.74]])

In [32]:
np.concatenate([x1,x2], axis=1)

array([[  4.35, -10.53,  -6.53,  -4.99,   4.21,  -1.34,  -4.35,   2.7 ,
         26.87,   2.69],
       [  5.25,  -1.05,  18.16,   1.43,  -3.38, -13.09,   6.83,  -2.84,
          5.46,  -8.74]])

In [34]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a     4.35
b   -10.53
c    -6.53
d    -4.99
e     4.21
dtype: float64

In [36]:
s2 = pd.Series(x2[0], index=['c','d','e','f','g'])
s2

c   -1.34
d   -4.35
e    2.70
f   26.87
g    2.69
dtype: float64

In [38]:
pd.concat([s1,s2], axis=1)

0     1
a   4.35   NaN
b -10.53   NaN
c  -6.53 -1.34
d  -4.99 -4.35
e   4.21  2.70
f    NaN 26.87
g    NaN  2.69